lib/adellis_web/router.ex
defmodule AdellisWeb.Router do
  use AdellisWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", AdellisWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)
    get("/about", PageController, :about)
    get("/contact", PageController, :contact)

    get("/products", ProductController, :index)
    get("/products/:nsn", ProductController, :show)

    post("/quote", QuoteController, :create)
  end

  scope "/api", AdellisWeb, as: :api do
    pipe_through(:api)

    scope "/v1", V1, as: :v1 do
      post("/products", ProductController, :search)
      get("/products", ProductController, :index)
      get("/products/:part_number", ProductController, :show)
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", AdellisWeb do
  #   pipe_through :api
  # end
end

lib/adellis/sales/quote.ex
defmodule Adellis.Sales.Quote do
  use Ecto.Schema
  import Ecto.Changeset

  schema "quotes" do
    field(:company_name, :string)
    field(:email_address, :string)
    field(:first_name, :string)
    field(:last_name, :string)
    field(:phone_number, :string)

    timestamps()
  end

  @doc false
  def changeset(quote, attrs) do
    quote
    |> cast(attrs, [:first_name, :last_name, :company_name, :phone_number, :email_address])
    |> validate_required([:first_name, :last_name, :company_name, :phone_number, :email_address])
  end
end

lib/adellis_web/controllers/quote_controller.ex
defmodule AdellisWeb.QuoteController do
  use AdellisWeb, :controller
  alias Adellis.Sales

  def create(conn, %{"quote" => quote_params}) do
    case Sales.create_quote(quote_params) do
      {:ok, _quote} ->
        conn
        |> put_flash(:info, "Quote submitted successfully")
        |> redirect(to: page_path(conn, :index))

      {:error, changeset} ->
        conn
        |> put_view(AdellisWeb.ProductView)
        |> render(:index, changeset: changeset)
    end
  end
end

lib/adellis_web/views/quote_view.ex
defmodule AdellisWeb.QuoteView do
  use AdellisWeb, :view
end

lib/adellis_web/templates/quote/quote_form.html.eex
<%= form_for @changeset, quote_path(@conn, :create), [as: :quote, id: "quote-form"], fn f -> %>

  <%= if @changeset.action do %>
    <div id='form-error' class="alert alert-danger">
     <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      <h4>Please check the form for errors</h4>
    </div>
  <% end %>

  <div class='form-row'>
    <div class='col form-group'>
      <%= label f , :first_name%>
      <%= text_input f, :first_name, class: "form-control" %>
      <%= error_tag f, :first_name %>
    </div>
    <div class='col form-group'>
      <%= label f , :last_name %>
      <%= text_input f, :last_name, class: "form-control" %>
      <%= error_tag f, :last_name %>
    </div>
  </div>
  <div class='form-row'>
    <div class='col form-group'>
      <%= label f , :email_address %>
      <%= text_input f, :email_address, class: "form-control" %>
      <%= error_tag f, :email_address %>
    </div>
    <div class='col form-group'>
      <%= label f , :phone_number %>
      <%= text_input f, :phone_number, class: "form-control" %>
      <%= error_tag f, :phone_number %>
    </div>
  </div>
  <div class='form-row '>
    <div class='col  form-group'>
      <%= label f , :company_name %>
      <%= text_input f, :company_name, class: "form-control" %>
      <%= error_tag f, :company_name %>
    </div>
  </div>
  <br>
  <%= submit "Quote", class: "btn btn-lg btn-info" %>
<% end %>